### PR TITLE
Move all sources one level up

### PR DESCRIPTION
**Pull request by MisterDA**
I think this helps discoverability and suppresses redundancies.

### CODE REVIEW

**Comment by MisterDA** [comment]
Please don't merge this one before the other PRs or I'll have to rebase them…

**Comment by moyodiallo** [comment]
> Please don't merge this one before the other PRs or I'll have to rebase them…

Could you draft it ?

**Comment by MisterDA** [comment]
I've changed my mind, you can merge it if you want, and I'll rebase the others.

**Comment by moyodiallo** [comment]
We need to go further.  To move the files from `service/bin` and `service/lib` to  `service`, do the same with `worker`.

**Comment by MisterDA** [comment]
I think that's ok honestly :)

**Comment by MisterDA** [comment]
I think that's ok honestly :-)

**Comment by MisterDA** [comment]
Please do

**Comment by MisterDA** [comment]
When you're happy I suggest you squash and merge.

**Pull request merged**
